import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import SparklesBackground from '@/components/sparkles-background';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      className='h-full scroll-smooth antialiased bg-transparent overflow-y-visible'>
      <body className='flex h-full flex-col'>
        <SparklesBackground>{children}</SparklesBackground>
      </body>
    </html>
  );
}
